-- Migration 002: Seed Bible Books
-- Created: 2024-01-01
-- Description: Insert 66 Bible books (39 Old Testament + 27 New Testament)

-- Old Testament Books (39 books)
INSERT INTO bible_books (name, abbreviation, chapter_count, testament, order_index) VALUES
('Sáng Thế Ký', 'STK', 50, 'Cựu Ước', 1),
('Xuất Ê-díp-tô Ký', 'XEDK', 40, 'Cựu Ước', 2),
('Lê-vi Ký', 'LVK', 27, 'Cựu Ước', 3),
('Dân Số Ký', 'DSK', 36, 'Cựu Ước', 4),
('Phục Truyền Luật Lệ Ký', 'PTLLK', 34, 'Cựu Ước', 5),
('Giô-suê', 'GS', 24, 'Cựu Ước', 6),
('Các Quan Xét', 'CQX', 21, 'Cựu Ước', 7),
('Ru-tơ', 'RT', 4, 'Cựu Ước', 8),
('I Sa-mu-ên', 'IS', 31, 'Cựu Ước', 9),
('II Sa-mu-ên', 'IIS', 24, 'Cựu Ước', 10),
('I Các Vua', 'ICV', 22, 'Cựu Ước', 11),
('II Các Vua', 'IICV', 25, 'Cựu Ước', 12),
('I Sử Ký', 'ISK', 29, 'Cựu Ước', 13),
('II Sử Ký', 'IISK', 36, 'Cựu Ước', 14),
('Ê-xơ-ra', 'EX', 10, 'Cựu Ước', 15),
('Nê-hê-mi', 'NH', 13, 'Cựu Ước', 16),
('Ê-xơ-tê', 'EXT', 10, 'Cựu Ước', 17),
('Gióp', 'G', 42, 'Cựu Ước', 18),
('Thi Thiên', 'TT', 150, 'Cựu Ước', 19),
('Châm Ngôn', 'CN', 31, 'Cựu Ước', 20),
('Truyền Đạo', 'TD', 12, 'Cựu Ước', 21),
('Nhã Ca', 'NC', 8, 'Cựu Ước', 22),
('Ê-sai', 'ES', 66, 'Cựu Ước', 23),
('Giê-rê-mi', 'GR', 52, 'Cựu Ước', 24),
('Ca Thương', 'CT', 5, 'Cựu Ước', 25),
('Ê-xê-chi-ên', 'EXC', 48, 'Cựu Ước', 26),
('Đa-ni-ên', 'DN', 12, 'Cựu Ước', 27),
('Ô-sê', 'OS', 14, 'Cựu Ước', 28),
('Giô-ên', 'GL', 3, 'Cựu Ước', 29),
('A-mốt', 'AM', 9, 'Cựu Ước', 30),
('Áp-đia', 'AD', 1, 'Cựu Ước', 31),
('Giô-na', 'GN', 4, 'Cựu Ước', 32),
('Mi-chê', 'MC', 7, 'Cựu Ước', 33),
('Na-hum', 'NH', 3, 'Cựu Ước', 34),
('Ha-ba-cúc', 'HB', 3, 'Cựu Ước', 35),
('Sô-phô-ni', 'SP', 3, 'Cựu Ước', 36),
('A-ghê', 'AG', 2, 'Cựu Ước', 37),
('Xa-cha-ri', 'XC', 14, 'Cựu Ước', 38),
('Ma-la-chi', 'MC', 4, 'Cựu Ước', 39);

-- New Testament Books (27 books)
INSERT INTO bible_books (name, abbreviation, chapter_count, testament, order_index) VALUES
('Ma-thi-ơ', 'MT', 28, 'Tân Ước', 40),
('Mác', 'MC', 16, 'Tân Ước', 41),
('Lu-ca', 'LC', 24, 'Tân Ước', 42),
('Giăng', 'GN', 21, 'Tân Ước', 43),
('Công Vụ Các Sứ Đồ', 'CVCSD', 28, 'Tân Ước', 44),
('Rô-ma', 'RM', 16, 'Tân Ước', 45),
('I Cô-rinh-tô', 'ICR', 16, 'Tân Ước', 46),
('II Cô-rinh-tô', 'IICR', 13, 'Tân Ước', 47),
('Ga-la-ti', 'GL', 6, 'Tân Ước', 48),
('Ê-phê-sô', 'EP', 6, 'Tân Ước', 49),
('Phi-líp', 'PL', 4, 'Tân Ước', 50),
('Cô-lô-se', 'CL', 4, 'Tân Ước', 51),
('I Tê-sa-lô-ni-ca', 'ITS', 5, 'Tân Ước', 52),
('II Tê-sa-lô-ni-ca', 'IITS', 3, 'Tân Ước', 53),
('I Ti-mô-thê', 'ITM', 6, 'Tân Ước', 54),
('II Ti-mô-thê', 'IITM', 4, 'Tân Ước', 55),
('Tít', 'TT', 3, 'Tân Ước', 56),
('Phi-lê-môn', 'PLM', 1, 'Tân Ước', 57),
('Hê-bơ-rơ', 'HB', 13, 'Tân Ước', 58),
('Gia-cơ', 'GC', 5, 'Tân Ước', 59),
('I Phi-e-rơ', 'IPR', 5, 'Tân Ước', 60),
('II Phi-e-rơ', 'IIPR', 3, 'Tân Ước', 61),
('I Giăng', 'IG', 5, 'Tân Ước', 62),
('II Giăng', 'IIG', 1, 'Tân Ước', 63),
('III Giăng', 'IIIG', 1, 'Tân Ước', 64),
('Giu-đe', 'GD', 1, 'Tân Ước', 65),
('Khải Huyền', 'KH', 22, 'Tân Ước', 66);

